auto: true
server: true
#markdown: rdiscount
permalink: /:year/:month/:day/:title
#rdiscount extensions: [smart]
exclude: dkschool.sublime-project dkschool.sublime-workspace Drupal.sublime-projectcompletions
host: dontknow-net.github.io
