auto: true
server: true
exclude:
  - dkschool.sublime-project
  - dkschool.sublime-workspace
  - Drupal.sublime-projectcompletions
host: dontknow-net.github.io
permalink: /curso/:title
prose:
  siteurl: http://www.dontknowschool.com/
  metadata:
    _posts/cursos:
      - name: "layout"
        field:
          element: "text"
          label: "Plantilla"
          value: "curso"


